# Generated by Django 5.2.11 on 2026-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
