# Generated by Django 5.2.11 on 2026-02-20 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
